"""create files and records tables

Revision ID: 0fc8508e82bb
Revises: None
Create Date: 2025-10-09 13:51:15.058758
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0fc8508e82bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_name', sa.String(length=512), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_name', 'etag', name='uq_blob_etag')
    )
    op.create_index(op.f('ix_files_blob_name'), 'files', ['blob_name'], unique=False)
    op.create_index(op.f('ix_files_etag'), 'files', ['etag'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('soap_corr_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_file_id'), 'records', ['file_id'], unique=False)
    op.create_index('ix_records_file_status', 'records', ['file_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_file_status', table_name='records')
    op.drop_index(op.f('ix_records_file_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_files_etag'), table_name='files')
    op.drop_index(op.f('ix_files_blob_name'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
